import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My first Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full justify-between px-10">
          <h1 className="font-bold"> front</h1>
          <div>
            <li className="flex gap-5 font-semibold">
              <ul>home</ul>
              <ul>about</ul>
              <ul>contact us</ul>
            </li>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
