name = "backend"
compatibility_date = "2024-08-14"

[vars]
DATABASE_URL=""

JWT_SECRET=""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE" 
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"